# Modifications © 2020 Hashmap, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: 2

sources:
  - name: tpch
    description: Sample TPC-H Benchmark data on Snowflake
    database: snowflake_sample_data
    schema: tpch_sf1
    tables:
      - name: customer
        description: Table with customer related information
        columns:
          - name: c_custkey
            description: Primary Key
            tests:
              - unique
              - is_nonnegative
          - name: c_name
            description: Customer name
          - name: c_nationkey
            description: Foreign key for nation dataset
            tests:
              - is_nonnegative
      - name: lineitem
        description: Table with order item related information
        columns:
          - name: l_orderkey
            description: Foreign Key to order
          - name: l_extendedprice
            description: Price before discount or tax is applied
            tests:
              - is_nonnegative
          - name: l_discount
            description: Relative amount that product was discounted
          - name: l_tax
            description: Tax rate for purchase
      - name: orders
        description: Table with customer orders
        columns:
          - name: o_orderkey
            description: Primary Key
            tests:
              - unique
          - name: o_custkey
            description: Foreign Key
            tests:
              - is_nonnegative
          - name: o_totalprice
            description: Total price of order including discounts and tax
          - name: o_orderdate
            description: Date that order was made by customer
      - name: nation
        description: Table with information related to a customers nation
        columns:
          - name: n_nationkey
            description: Primary Key
            tests:
              - unique
              - is_nonnegative
          - name: n_name
            description: Nations name